// ─────────────────────────────────────────────────────────────────────────────
//  Switch Captain — Community Data Layer
//  All community data stays in localStorage. Keys never conflict with existing.
// ─────────────────────────────────────────────────────────────────────────────
import toast from 'react-hot-toast';
import { getCandidates, getCaptains, getSettings, type Candidate, type Captain } from './data';

// ─── STORAGE KEYS ────────────────────────────────────────────────────────────
export const COMM_KEYS = {
  communities:     'switch_communities',
  communityPosts:  'switch_community_posts',
  broadcasts:      'switch_broadcasts',
  polls:           'switch_polls',
  workerProfiles:  'switch_worker_profiles',
  rehireLog:       'switch_rehire_log',
};

// ─── TYPES ───────────────────────────────────────────────────────────────────
export interface Community {
  id:          string;
  captainId:   string;
  captainName: string;
  name:        string;
  coverColor:  string;
  createdAt:   string;
  memberIds:   string[];
  pinnedPostId: string | null;
  stats: {
    totalMembers:      number;
    activePlacements:  number;
    available:         number;
    rehires:           number;
  };
}

export interface CommunityPost {
  id:          string;
  communityId: string;
  captainId:   string;
  type:        'announcement' | 'job' | 'milestone' | 'auto_success';
  content:     string;
  reactions:   { thumbsUp: number; fire: number };
  postedAt:    string;
  pinned:      boolean;
  autoGenerated: boolean;
}

export interface Broadcast {
  id:            string;
  fromCaptainId: string;
  communityId:   string;
  jobTitle:      string;
  location:      string;
  salary:        string;
  message:       string;
  targetFilter:  { jobTypes: string[]; availableOnly: boolean };
  sentAt:        string;
  seenBy:        string[];
  respondedBy:   string[];
}

export interface Poll {
  id:          string;
  communityId: string;
  question:    string;
  options:     string[];
  responses:   Record<string, string>;
  createdAt:   string;
  expiresAt:   string;
  active:      boolean;
}

export interface WorkerProfile {
  id:            string;
  candidateId:   string;
  name:          string;
  mobile:        string;
  currentStage:  string;
  jobType:       string;
  location:      string;
  statusMessage: string;
  lastUpdated:   string;
}

export interface RehireLog {
  id:                   string;
  originalCandidateId:  string;
  originalPlacedAt:     string | null;
  rehireSubmittedAt:    string;
  rehireSubmittedBy:    string;
  newPipelineEntryId:   string;
  payoutAmount:         number;
  payoutStatus:         'pending' | 'confirmed' | 'paid';
  billedToOps:          boolean;
}

// ─── COVER COLORS ─────────────────────────────────────────────────────────────
export const COVER_COLORS = [
  { value: '#1A7A4A', label: 'Switch Green' },
  { value: '#185FA5', label: 'Steel Blue' },
  { value: '#854F0B', label: 'Warm Amber' },
  { value: '#534AB7', label: 'Deep Purple' },
  { value: '#993C1D', label: 'Burnt Coral' },
  { value: '#0F6E56', label: 'Forest Teal' },
];

const STATUS_MESSAGES: Record<string, string> = {
  Sourced:      'Your profile has been received. We\'ll be in touch soon.',
  Screening:    'Your profile is being reviewed by our team.',
  Interviewed:  'Your interview details are being processed. Expect a call soon.',
  Offered:      'Great news! An offer is being prepared for you.',
  Placed:       'Congratulations! You have been successfully placed.',
};

// ─── GETTERS ─────────────────────────────────────────────────────────────────
export function getCommunities(): Community[] {
  return JSON.parse(localStorage.getItem(COMM_KEYS.communities) || '[]');
}
export function getCommunityPosts(): CommunityPost[] {
  return JSON.parse(localStorage.getItem(COMM_KEYS.communityPosts) || '[]');
}
export function getBroadcasts(): Broadcast[] {
  return JSON.parse(localStorage.getItem(COMM_KEYS.broadcasts) || '[]');
}
export function getPolls(): Poll[] {
  return JSON.parse(localStorage.getItem(COMM_KEYS.polls) || '[]');
}
export function getWorkerProfiles(): WorkerProfile[] {
  return JSON.parse(localStorage.getItem(COMM_KEYS.workerProfiles) || '[]');
}
export function getRehireLog(): RehireLog[] {
  return JSON.parse(localStorage.getItem(COMM_KEYS.rehireLog) || '[]');
}

// ─── SETTERS ─────────────────────────────────────────────────────────────────
function saveCommunities(d: Community[])   { localStorage.setItem(COMM_KEYS.communities,    JSON.stringify(d)); }
function savePosts(d: CommunityPost[])     { localStorage.setItem(COMM_KEYS.communityPosts, JSON.stringify(d)); }
function saveBroadcasts(d: Broadcast[])    { localStorage.setItem(COMM_KEYS.broadcasts,     JSON.stringify(d)); }
function savePolls(d: Poll[])              { localStorage.setItem(COMM_KEYS.polls,           JSON.stringify(d)); }
function saveWorkerProfiles(d: WorkerProfile[]) { localStorage.setItem(COMM_KEYS.workerProfiles, JSON.stringify(d)); }
function saveRehireLog(d: RehireLog[])     { localStorage.setItem(COMM_KEYS.rehireLog,       JSON.stringify(d)); }

// ─── COMMUNITY HELPERS ───────────────────────────────────────────────────────
export function getCommunity(captainId: string): Community | undefined {
  return getCommunities().find(c => c.captainId === captainId);
}

export function getCommunityById(id: string): Community | undefined {
  return getCommunities().find(c => c.id === id);
}

export function recalculateCommunityStats(communityId: string) {
  const communities = getCommunities();
  const idx = communities.findIndex(c => c.id === communityId);
  if (idx === -1) return;
  const community = communities[idx];
  const candidates = getCandidates();
  const members = candidates.filter(c => community.memberIds.includes(c.id));
  const rehires = getRehireLog().filter(r => r.rehireSubmittedBy === community.captainId).length;

  communities[idx] = {
    ...community,
    stats: {
      totalMembers:     community.memberIds.length,
      activePlacements: members.filter(c => c.currentStage === 'Placed').length,
      available:        members.filter(c => c.currentStage !== 'Placed' && c.placedAt).length,
      rehires,
    },
  };
  saveCommunities(communities);
  return communities[idx];
}

export function createCommunity(captainId: string, captainName: string, showToast = true): Community {
  const existing = getCommunity(captainId);
  if (existing) return existing;

  const community: Community = {
    id:          `comm_${captainId}`,
    captainId,
    captainName,
    name:        `${captainName.split(' ')[0]}'s Community`,
    coverColor:  COVER_COLORS[0].value,
    createdAt:   new Date().toISOString(),
    memberIds:   [],
    pinnedPostId: null,
    stats:       { totalMembers: 0, activePlacements: 0, available: 0, rehires: 0 },
  };

  const communities = getCommunities();
  communities.push(community);
  saveCommunities(communities);

  if (showToast) toast.success('🏘️ Your Switch community was created!');
  return community;
}

export function addMemberToCommunity(communityId: string, candidateId: string) {
  const communities = getCommunities();
  const idx = communities.findIndex(c => c.id === communityId);
  if (idx === -1) return;
  if (communities[idx].memberIds.includes(candidateId)) return; // idempotent
  communities[idx].memberIds.push(candidateId);
  saveCommunities(communities);
  recalculateCommunityStats(communityId);
}

export function renameCommunity(communityId: string, newName: string) {
  const communities = getCommunities();
  const idx = communities.findIndex(c => c.id === communityId);
  if (idx === -1) return;
  communities[idx].name = newName.trim();
  saveCommunities(communities);
}

export function setCommunityColor(communityId: string, color: string) {
  const communities = getCommunities();
  const idx = communities.findIndex(c => c.id === communityId);
  if (idx === -1) return;
  communities[idx].coverColor = color;
  saveCommunities(communities);
}

export function pinPost(communityId: string, postId: string | null) {
  const communities = getCommunities();
  const idx = communities.findIndex(c => c.id === communityId);
  if (idx === -1) return;
  communities[idx].pinnedPostId = postId;
  saveCommunities(communities);
  const posts = getCommunityPosts();
  const updated = posts.map(p =>
    p.communityId === communityId ? { ...p, pinned: p.id === postId } : p
  );
  savePosts(updated);
}

// ─── AUTO-TRIGGERS ────────────────────────────────────────────────────────────
export function onLeadSubmitted(candidate: Candidate, captainId: string, captainName: string) {
  let community = getCommunity(captainId);
  if (!community) {
    community = createCommunity(captainId, captainName, true);
  }
  addMemberToCommunity(community.id, candidate.id);
  createOrUpdateWorkerProfile(candidate);
}

export function onCandidatePlaced(candidate: Candidate) {
  const communityId = `comm_${candidate.referredBy}`;
  createAutoSuccessPost(communityId, candidate);
  recalculateCommunityStats(communityId);
  createOrUpdateWorkerProfile(candidate);
}

export function createAutoSuccessPost(communityId: string, candidate: Candidate) {
  const community = getCommunityById(communityId);
  if (!community) return;
  const posts = getCommunityPosts();
  // idempotent guard
  if (posts.find(p => p.type === 'auto_success' && p.content.includes(candidate.id))) return;

  const totalPlaced = getCandidates().filter(
    c => community.memberIds.includes(c.id) && c.currentStage === 'Placed'
  ).length;

  const post: CommunityPost = {
    id:            `post_auto_${candidate.id}`,
    communityId,
    captainId:     community.captainId,
    type:          'auto_success',
    content:       `🎉 ${candidate.name} has been successfully placed as a ${candidate.jobType} in ${candidate.location}. Community total: ${totalPlaced} placements 🏆 [candidateId:${candidate.id}]`,
    reactions:     { thumbsUp: 0, fire: 0 },
    postedAt:      new Date().toISOString(),
    pinned:        false,
    autoGenerated: true,
  };
  posts.unshift(post);
  savePosts(posts);
}

// ─── POSTS ────────────────────────────────────────────────────────────────────
export function createPost(
  communityId: string, captainId: string,
  type: CommunityPost['type'], content: string
): CommunityPost {
  const post: CommunityPost = {
    id:            `post_${Date.now()}`,
    communityId, captainId, type, content,
    reactions:     { thumbsUp: 0, fire: 0 },
    postedAt:      new Date().toISOString(),
    pinned:        false,
    autoGenerated: false,
  };
  const posts = getCommunityPosts();
  posts.unshift(post);
  savePosts(posts);
  return post;
}

export function reactToPost(postId: string, reaction: 'thumbsUp' | 'fire') {
  const posts = getCommunityPosts();
  const idx = posts.findIndex(p => p.id === postId);
  if (idx === -1) return;
  posts[idx].reactions[reaction]++;
  savePosts(posts);
}

export function getPostsForCommunity(communityId: string): CommunityPost[] {
  return getCommunityPosts()
    .filter(p => p.communityId === communityId)
    .sort((a, b) => {
      if (a.pinned && !b.pinned) return -1;
      if (!a.pinned && b.pinned) return 1;
      return new Date(b.postedAt).getTime() - new Date(a.postedAt).getTime();
    });
}

// ─── BROADCASTS ──────────────────────────────────────────────────────────────
export function sendBroadcast(
  captainId: string, communityId: string,
  jobTitle: string, location: string, salary: string,
  message: string, targetFilter: Broadcast['targetFilter']
): Broadcast {
  const b: Broadcast = {
    id:            `bcast_${Date.now()}`,
    fromCaptainId: captainId,
    communityId,
    jobTitle, location, salary, message, targetFilter,
    sentAt:        new Date().toISOString(),
    seenBy:        [],
    respondedBy:   [],
  };
  const broadcasts = getBroadcasts();
  broadcasts.unshift(b);
  saveBroadcasts(broadcasts);

  // Also create a community post so it appears in the feed
  createPost(communityId, captainId, 'job',
    `📣 ${jobTitle} opening in ${location}${salary ? ` · ${salary}` : ''}. ${message}`
  );
  return b;
}

export function getBroadcastsForCommunity(communityId: string): Broadcast[] {
  return getBroadcasts()
    .filter(b => b.communityId === communityId)
    .sort((a, b) => new Date(b.sentAt).getTime() - new Date(a.sentAt).getTime());
}

// ─── POLLS ───────────────────────────────────────────────────────────────────
export function createPoll(communityId: string, options: string[], expiryDays = 7): Poll {
  const expires = new Date();
  expires.setDate(expires.getDate() + expiryDays);
  const poll: Poll = {
    id:          `poll_${Date.now()}`,
    communityId,
    question:    'Who is available for work this week?',
    options,
    responses:   {},
    createdAt:   new Date().toISOString(),
    expiresAt:   expires.toISOString(),
    active:      true,
  };
  const polls = getPolls();
  polls.unshift(poll);
  savePolls(polls);
  return poll;
}

export function respondToPoll(pollId: string, candidateId: string, option: string) {
  const polls = getPolls();
  const idx = polls.findIndex(p => p.id === pollId);
  if (idx === -1) return;
  polls[idx].responses[candidateId] = option;
  savePolls(polls);
}

export function getPollsForCommunity(communityId: string): Poll[] {
  return getPolls().filter(p => p.communityId === communityId);
}

export function getActivePollForCommunity(communityId: string): Poll | undefined {
  const now = new Date();
  return getPolls().find(p =>
    p.communityId === communityId && p.active && new Date(p.expiresAt) > now
  );
}

// ─── WORKER PROFILES ─────────────────────────────────────────────────────────
export function createOrUpdateWorkerProfile(candidate: Candidate) {
  const profiles = getWorkerProfiles();
  const idx = profiles.findIndex(p => p.candidateId === candidate.id);
  const profile: WorkerProfile = {
    id:            `wp_${candidate.id}`,
    candidateId:   candidate.id,
    name:          candidate.name,
    mobile:        candidate.mobile,
    currentStage:  candidate.currentStage,
    jobType:       candidate.jobType,
    location:      candidate.location,
    statusMessage: STATUS_MESSAGES[candidate.currentStage] || STATUS_MESSAGES.Sourced,
    lastUpdated:   new Date().toISOString(),
  };
  if (idx === -1) profiles.push(profile);
  else profiles[idx] = profile;
  saveWorkerProfiles(profiles);
  return profile;
}

export function getWorkerProfileByMobile(mobile: string): WorkerProfile | undefined {
  const clean = mobile.replace(/\D/g, '');
  return getWorkerProfiles().find(p => p.mobile.replace(/\D/g, '') === clean);
}

// ─── RE-HIRE ─────────────────────────────────────────────────────────────────
export function processRehire(
  originalCandidateId: string,
  captainId: string,
  newJobType: string,
  newLocation: string,
  addCandidateFn: (c: any) => Candidate
): { newCandidate: Candidate; rehireEntry: RehireLog } | null {
  const original = getCandidates().find(c => c.id === originalCandidateId);
  if (!original) return null;

  const settings = getSettings();
  const newCandidate = addCandidateFn({
    name:              original.name,
    mobile:            original.mobile,
    jobType:           newJobType || original.jobType,
    location:          newLocation || original.location,
    currentStage:      'Sourced',
    referredBy:        captainId,
    submittedAt:       new Date().toISOString(),
    placedAt:          null,
    guaranteeExpiresAt: null,
    replacementNeeded: false,
    isRehire:          true,
    originalCandidateId: original.id,
    currentJob:        '',
    payout:            { amount: settings.perHireFee, status: 'pending', paidAt: null },
    timeline:          [{ stage: 'Sourced', movedAt: new Date().toISOString(), movedBy: captainId, note: `Re-hire (original placed: ${original.placedAt?.split('T')[0] || 'N/A'})` }],
    notes:             [],
    flagged:           false,
    archived:          false,
  });

  const rehireEntry: RehireLog = {
    id:                   `rh_${Date.now()}`,
    originalCandidateId:  original.id,
    originalPlacedAt:     original.placedAt,
    rehireSubmittedAt:    new Date().toISOString(),
    rehireSubmittedBy:    captainId,
    newPipelineEntryId:   newCandidate.id,
    payoutAmount:         settings.perHireFee,
    payoutStatus:         'pending',
    billedToOps:          true,
  };
  const log = getRehireLog();
  log.unshift(rehireEntry);
  saveRehireLog(log);

  // increment rehires in community stats
  const communityId = `comm_${captainId}`;
  recalculateCommunityStats(communityId);

  return { newCandidate, rehireEntry };
}

export function getRehireOpportunities(captainId: string): Candidate[] {
  const community = getCommunity(captainId);
  if (!community) return [];
  const candidates = getCandidates();
  const rehireIds = new Set(getRehireLog().map(r => r.originalCandidateId));
  return candidates.filter(c =>
    community.memberIds.includes(c.id) &&
    c.currentStage === 'Placed' &&
    !rehireIds.has(c.id)
  );
}

// ─── MEMBER HELPERS ──────────────────────────────────────────────────────────
export type MemberStatus = 'placed' | 'available' | 'in_pipeline' | 'looking';

export function getMemberStatus(candidate: Candidate): MemberStatus {
  if (candidate.currentStage === 'Placed' && !candidate.archived) return 'placed';
  if (candidate.currentStage === 'Sourced' && candidate.placedAt) return 'looking';
  if (candidate.currentStage !== 'Sourced') return 'in_pipeline';
  return 'available';
}

export function getMemberStatusLabel(status: MemberStatus): string {
  const labels: Record<MemberStatus, string> = {
    placed:      'Placed',
    available:   'Available',
    in_pipeline: 'In Pipeline',
    looking:     'Looking',
  };
  return labels[status];
}

export function getMemberStatusColor(status: MemberStatus): { bg: string; color: string } {
  const colors: Record<MemberStatus, { bg: string; color: string }> = {
    placed:      { bg: '#E8F5EE', color: '#0F5C35' },
    available:   { bg: '#E8F5EE', color: '#1A7A4A' },
    in_pipeline: { bg: '#EFF6FF', color: '#1D4ED8' },
    looking:     { bg: '#FFF9E6', color: '#92400E' },
  };
  return colors[status];
}

export function getCommunityMembers(captainId: string): (Candidate & { status: MemberStatus })[] {
  const community = getCommunity(captainId);
  if (!community) return [];
  const candidates = getCandidates();
  return community.memberIds
    .map(id => candidates.find(c => c.id === id))
    .filter(Boolean)
    .map(c => ({ ...c!, status: getMemberStatus(c!) }));
}

// ─── OPS HELPERS ─────────────────────────────────────────────────────────────
export function getCommunityHealthScore(community: Community): number {
  let score = 0;
  const { totalMembers, activePlacements, rehires } = community.stats;
  if (totalMembers >= 20) score += 2; else if (totalMembers >= 10) score += 1;
  const rate = totalMembers > 0 ? activePlacements / totalMembers : 0;
  if (rate >= 0.3) score += 2; else if (rate >= 0.1) score += 1;
  if (rehires >= 3) score += 1;
  return Math.min(5, score);
}

export function getAllCommunitiesForOps(): (Community & { healthScore: number; captain: Captain | undefined })[] {
  const captains = getCaptains();
  return getCommunities().map(comm => ({
    ...comm,
    healthScore: getCommunityHealthScore(comm),
    captain: captains.find(c => c.id === comm.captainId),
  })).sort((a, b) => b.stats.totalMembers - a.stats.totalMembers);
}

export function getRehireAnalytics() {
  const log = getRehireLog();
  const candidates = getCandidates();
  const captains = getCaptains();

  const everPlaced = candidates.filter(c => c.currentStage === 'Placed').length;
  const markedAvailable = log.length;
  const captainSubmitted = log.length;
  const successfullyReplaced = log.filter(r => r.payoutStatus !== 'pending').length;

  const byCapt = captains.map(cap => ({
    captain: cap,
    rehires: log.filter(r => r.rehireSubmittedBy === cap.id).length,
    revenue: log.filter(r => r.rehireSubmittedBy === cap.id && r.payoutStatus === 'paid')
               .reduce((s, r) => s + r.payoutAmount, 0),
  })).filter(r => r.rehires > 0).sort((a, b) => b.rehires - a.rehires);

  return { everPlaced, markedAvailable, captainSubmitted, successfullyReplaced, byCapt };
}

// ─── SEED DATA ────────────────────────────────────────────────────────────────
export function initCommunitySeedData() {
  if (localStorage.getItem('switch_community_seed_v1')) return;

  const candidates = getCandidates();
  const captains = getCaptains();
  if (captains.length === 0 || candidates.length === 0) return;

  const dAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

  // Build one community per captain, auto-assign all candidates
  const communities: Community[] = captains.map((cap, i) => {
    const myCandidates = candidates.filter(c => c.referredBy === cap.id);
    const colors = COVER_COLORS.map(c => c.value);
    return {
      id:          `comm_${cap.id}`,
      captainId:   cap.id,
      captainName: cap.name,
      name:        `${cap.name.split(' ')[0]}'s Community`,
      coverColor:  colors[i % colors.length],
      createdAt:   dAgo(30 - i * 5),
      memberIds:   myCandidates.map(c => c.id),
      pinnedPostId: null,
      stats: {
        totalMembers:     myCandidates.length,
        activePlacements: myCandidates.filter(c => c.currentStage === 'Placed').length,
        available:        myCandidates.filter(c => c.currentStage !== 'Placed' && c.placedAt).length,
        rehires:          i < 2 ? i + 1 : 0,
      },
    };
  });
  saveCommunities(communities);

  // Seed posts
  const posts: CommunityPost[] = [];
  communities.forEach(comm => {
    posts.push({
      id:            `post_seed_${comm.id}_1`,
      communityId:   comm.id,
      captainId:     comm.captainId,
      type:          'announcement',
      content:       `Welcome to ${comm.name}! I'll be sharing job opportunities and updates here regularly. Stay tuned! 🎯`,
      reactions:     { thumbsUp: 5, fire: 2 },
      postedAt:      dAgo(20),
      pinned:        false,
      autoGenerated: false,
    });
    posts.push({
      id:            `post_seed_${comm.id}_2`,
      communityId:   comm.id,
      captainId:     comm.captainId,
      type:          'milestone',
      content:       `🏆 Milestone reached! Our community has grown to ${comm.stats.totalMembers} members. Thank you for your trust!`,
      reactions:     { thumbsUp: 12, fire: 7 },
      postedAt:      dAgo(10),
      pinned:        false,
      autoGenerated: true,
    });
  });

  // Seed broadcasts
  const broadcasts: Broadcast[] = [{
    id:            'bcast_seed_001',
    fromCaptainId: captains[0]?.id || '',
    communityId:   `comm_${captains[0]?.id || ''}`,
    jobTitle:      'Security Guard',
    location:      'DLF Phase 2',
    salary:        '₹13,000/mo',
    message:       '3 urgent openings this week. Priority to those available immediately.',
    targetFilter:  { jobTypes: ['Security Guard'], availableOnly: true },
    sentAt:        dAgo(2),
    seenBy:        candidates.slice(0, 2).map(c => c.id),
    respondedBy:   candidates.slice(0, 1).map(c => c.id),
  }];
  saveBroadcasts(broadcasts);

  // Seed polls
  const expiresAt = new Date(Date.now() + 5 * 86400000).toISOString();
  const polls: Poll[] = [{
    id:          'poll_seed_001',
    communityId: `comm_${captains[0]?.id || ''}`,
    question:    'Who is available for work this week?',
    options:     ['Available now', 'Available next week', 'Currently working'],
    responses:   Object.fromEntries(candidates.slice(0, 3).map((c, i) => [c.id, ['Available now', 'Currently working', 'Available next week'][i % 3]])),
    createdAt:   dAgo(3),
    expiresAt,
    active:      true,
  }];
  savePolls(polls);

  // Seed rehire log
  const placed = candidates.filter(c => c.currentStage === 'Placed');
  const rehireLog: RehireLog[] = placed.slice(0, 2).map((c, i) => ({
    id:                   `rh_seed_00${i + 1}`,
    originalCandidateId:  c.id,
    originalPlacedAt:     c.placedAt,
    rehireSubmittedAt:    dAgo(5 - i),
    rehireSubmittedBy:    c.referredBy,
    newPipelineEntryId:   `cand_rehire_00${i + 1}`,
    payoutAmount:         300,
    payoutStatus:         i === 0 ? 'paid' : 'pending',
    billedToOps:          true,
  }));
  saveRehireLog(rehireLog);

  // Seed worker profiles for all candidates
  candidates.forEach(c => createOrUpdateWorkerProfile(c));

  savePosts(posts);

  localStorage.setItem('switch_community_seed_v1', 'true');
}
